"""Distill genome-scale FBA capability into the ranker architecture.

The fusion the user asked for: the original BioCandidateRanker model should
itself be able to answer the questions iML1515 and iJO1366 answer — given a
medium and a genetic scenario, what growth does the cell achieve? — without
invoking cobra at inference.

This module trains ranker checkpoints on simulation grids generated by
biocandidate.fba_context. The scenario (medium bounds, knockout flag,
overexpression factors, fusion caps) is encoded as the 8-wide fba_context
input; the FBA-computed biomass flux is the log10_flux label. Protein and
molecule modalities are disabled, exactly as in the governed simulated-flux
smoke, so the trained pathway is the fba_context one.

Claim boundary: the checkpoints are surrogates of simulations. They are not
experimental flux models, they do not replace the GEM outside the sampled
scenario distribution, and they make no scientific claim about real cells.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import random
from pathlib import Path
from typing import Any

import torch
from torch.utils.data import DataLoader

from .data import (
    CANONICAL_LOG10_FLUX_UNIT,
    EnzymeSubstrateCollator,
    EnzymeSubstrateRecord,
    FBAFeatureMetadata,
    FluxLabelMetadata,
    FluxLabelType,
)
from .fba_context import (
    GLUCOSE_EXCHANGE,
    MODEL_REGISTRY,
    OXYGEN_EXCHANGE,
    CLAIM_BOUNDARY as FBA_CLAIM_BOUNDARY,
    load_model,
    load_model_config,
)
from .training import BioCandidateRanker, ModelConfig, RecordDataset, run_epoch, save_checkpoint

SURROGATE_CLAIM_BOUNDARY = (
    "Trained surrogate of iML1515/iJO1366 simulations: the model imitates FBA "
    "outputs over the sampled scenario distribution. It is not an experimental "
    "flux model, does not replace the GEM outside that distribution, and "
    "carries no validation claim for real cells."
)

SOURCE_DATASET = "fba-surrogate-v1"

# Inference-time carrier must match the training records exactly: with
# use_context=True the context fields (organism, EC, enzyme type, reaction)
# are hashed into the forward pass, so a default-valued candidate would
# query a context the surrogate never saw.
CARRIER_CONTEXT = {
    "organism": "Escherichia coli (model context only)",
    "ec": "not_applicable",
    "enzyme_type": "simulated_fba_condition",
}

# Scenario-input features: the 8-wide fba_context contract for surrogates.
SCENARIO_FEATURE_IDS = (
    "medium_lower_bound:EX_glc__D_e",
    "medium_lower_bound:EX_o2_e",
    "cap:NOG_F6P",
    "medium_lower_bound:EX_phite_e",
    "medium_lower_bound:EX_co2_e",
    "knockout:ptsG",
    "overexpression:THD2pp",
    "overexpression:NADK",
)

GLUCOSE_GRID = (3.0, 6.0, 9.0, 12.0, 15.0, 18.0)
OXYGEN_GRID = (0.0, 3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 20.0, 21.0)

# Modification scenarios per model, mirroring fba_context presets.
IML1515_SCENARIOS = (
    {"name": "baseline"},
    {"name": "ptsG_knockout"},
    {"name": "thd2pp_overexpression", "oe": ("THD2pp", 1.5)},
    {"name": "nadK_overexpression", "oe": ("NADK", 1.5)},
    {"name": "paper_stack", "ko": True, "oe": ("THD2pp", 1.5)},
)
IJO1366_SCENARIOS = (
    {"name": "baseline"},
    {"name": "ptsG_knockout"},
    {"name": "thd2pp_overexpression", "oe": ("THD2pp", 1.5)},
    {"name": "fusion_M2_NOG", "fusion": {"nog": 3.0, "phosphite": 0.0}},
    {"name": "fusion_M3_PtxD", "fusion": {"nog": 0.0, "phosphite": 5.0}},
    {"name": "fusion_M5_NOG_PtxD", "fusion": {"nog": 3.0, "phosphite": 5.0}},
)

SPLITS = ("train", "validation", "test")


def _scenario_vector(scenario: dict[str, Any], glucose: float, oxygen: float) -> tuple[float, ...]:
    """Encode one scenario as the 8-wide scenario-input vector."""
    fusion = scenario.get("fusion") or {}
    return (
        float(glucose),
        float(oxygen),
        float(fusion.get("nog", 0.0)),
        float(fusion.get("phosphite", 0.0)),
        float(FUSION_CO2_CAP if fusion else 0.0),
        1.0 if scenario.get("ko") else 0.0,
        float(scenario["oe"][1]) if scenario.get("oe") else 0.0,
        0.0,
    )


FUSION_CO2_CAP = 5.0


def build_scenarios(model_id: str) -> list[dict[str, Any]]:
    """Enumerate the full grid: medium combos crossed with genetic scenarios."""
    scenarios = IML1515_SCENARIOS if model_id == "iML1515" else IJO1366_SCENARIOS
    rows = []
    for scenario in scenarios:
        for glucose in GLUCOSE_GRID:
            for oxygen in OXYGEN_GRID:
                rows.append(
                    {
                        "model_id": model_id,
                        "scenario": scenario,
                        "glucose": glucose,
                        "oxygen": oxygen,
                    }
                )
    return rows


def _condition_hash(model_id: str, scenario_name: str, glucose: float, oxygen: float) -> str:
    payload = json.dumps(
        {"model": model_id, "scenario": scenario_name, "glucose": glucose, "oxygen": oxygen},
        sort_keys=True,
    ).encode("utf-8")
    return "sha256:" + hashlib.sha256(payload).hexdigest()


def run_fba_grid(
    model_id: str,
    *,
    model=None,
    model_sha256: str | None = None,
) -> dict[str, Any]:
    """Solve every scenario in the grid on ONE model copy.

    Bound changes are reverted between scenarios, so a single copy serves the
    whole sweep; each returned row carries the objective flux plus the scenario
    identity needed for training records.
    """
    if model_id not in MODEL_REGISTRY:
        raise ValueError(f"unknown model {model_id!r}; known: {sorted(MODEL_REGISTRY)}")
    from .fba_context import add_fusion_pathways

    spec = MODEL_REGISTRY[model_id]
    base = model if model is not None else load_model(model_id)
    scoped = base.copy()
    scoped.objective = spec["objective_id"]

    use_fusion = any(row["scenario"].get("fusion") for row in build_scenarios(model_id))
    if use_fusion:
        add_fusion_pathways(scoped)

    rows: list[dict[str, Any]] = []
    dropped: list[dict[str, Any]] = []
    for row in build_scenarios(model_id):
        scenario = row["scenario"]
        glucose, oxygen = row["glucose"], row["oxygen"]

        with scoped:
            scoped.reactions.get_by_id(GLUCOSE_EXCHANGE).lower_bound = -float(glucose)
            scoped.reactions.get_by_id(OXYGEN_EXCHANGE).lower_bound = -float(oxygen)
            if scenario.get("fusion"):
                caps = scenario["fusion"]
                scoped.reactions.EX_co2_e.lower_bound = -FUSION_CO2_CAP
                scoped.reactions.NOG_F6P.upper_bound = float(caps["nog"])
                scoped.reactions.EX_phite_e.lower_bound = -float(caps["phosphite"])
                if caps["phosphite"] == 0:
                    scoped.reactions.PTXD.upper_bound = 0.0

            ko_targets = []
            if scenario.get("ko"):
                gene = next(g for g in scoped.genes if g.name == "ptsG" or g.id == "ptsG")
                for reaction in gene.reactions:
                    ko_targets.append((reaction, reaction.lower_bound, reaction.upper_bound))
                    reaction.bounds = (0.0, 0.0)
            oe_target = None
            if scenario.get("oe"):
                rid, factor = scenario["oe"]
                reaction = scoped.reactions.get_by_id(rid)
                baseline = scoped.optimize()
                optimum = float(baseline.fluxes[rid]) if baseline.status == "optimal" else 0.0
                if optimum > 0:
                    oe_target = (reaction, reaction.lower_bound)
                    reaction.lower_bound = factor * optimum

            solution = scoped.optimize()

            for reaction, lb, ub in ko_targets:
                reaction.bounds = (lb, ub)
            if oe_target:
                oe_target[0].lower_bound = oe_target[1]

        growth = None
        if solution.status == "optimal":
            value = float(solution.objective_value)
            growth = value if value > 1e-9 else None
        if growth is None:
            dropped.append({"scenario": scenario["name"], "glucose": glucose, "oxygen": oxygen})
            continue

        rows.append(
            {
                "model_id": model_id,
                "scenario_name": scenario["name"],
                "glucose": glucose,
                "oxygen": oxygen,
                "features": list(_scenario_vector(scenario, glucose, oxygen)),
                "log10_growth": math.log10(growth),
                "growth": growth,
                "condition_id": _condition_hash(model_id, scenario["name"], glucose, oxygen),
            }
        )

    return {
        "model_id": model_id,
        "rows": rows,
        "dropped": dropped,
        "feature_ids": list(SCENARIO_FEATURE_IDS),
        "objective_id": spec["objective_id"],
        "model_sha256": model_sha256,
        "claim_boundary": SURROGATE_CLAIM_BOUNDARY,
        "fba_claim_boundary": FBA_CLAIM_BOUNDARY,
    }


def _record(row: dict[str, Any], fba_payload: dict[str, Any], source_row: int) -> EnzymeSubstrateRecord:
    return EnzymeSubstrateRecord(
        sequence="X",
        substrate_smiles="O",
        organism="Escherichia coli (model context only)",
        ec="not_applicable",
        enzyme_type="simulated_fba_condition",
        candidate_id=row["condition_id"],
        reaction=fba_payload["objective_id"],
        fba_context=tuple(row["features"]),
        fba_feature_metadata=FBAFeatureMetadata(
            schema_version=1,
            feature_ids=tuple(fba_payload["feature_ids"]),
            model_id=row["model_id"],
            solver_id="glpk",
            objective_id=fba_payload["objective_id"],
            condition_id=row["condition_id"],
        ),
        log10_flux=row["log10_growth"],
        flux_label_metadata=FluxLabelMetadata(
            label_type=FluxLabelType.SIMULATED,
            target_reaction_id=fba_payload["objective_id"],
            canonical_unit=CANONICAL_LOG10_FLUX_UNIT,
            provenance_json=json.dumps(
                {
                    "scenario": row["scenario_name"],
                    "glucose": row["glucose"],
                    "oxygen": row["oxygen"],
                    "model_sha256": fba_payload.get("model_sha256"),
                },
                sort_keys=True,
            ),
        ),
        source_dataset=f"{SOURCE_DATASET}-{row['model_id']}",
        source_row=source_row,
        split=row["split"],
    )


def assign_splits(rows: list[dict[str, Any]]) -> None:
    """Deterministic ~72/14/14 split: sort by condition hash, then slice.

    The hash sort pseudo-randomizes the order, so proportional slices of the
    sorted list are random samples; max(1, n//7) per minor partition keeps
    validation and test non-empty even on miniature grids.
    """
    ordered = sorted(rows, key=lambda row: row["condition_id"])
    n_val = max(1, len(ordered) // 7)
    n_test = max(1, len(ordered) // 7)
    for index, row in enumerate(ordered):
        if index < n_val:
            row["split"] = "validation"
        elif index < n_val + n_test:
            row["split"] = "test"
        else:
            row["split"] = "train"


def train_surrogate(
    model_id: str,
    output_dir: str | Path,
    *,
    epochs: int = 120,
    seed: int = 7,
) -> dict[str, Any]:
    """Generate the grid, train a context-only ranker, evaluate, and freeze it."""
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    config_file = load_model_config(model_id)

    grid = run_fba_grid(model_id, model_sha256=config_file["sha256"])
    assign_splits(grid["rows"])
    dataset_path = output / "simulated_flux.jsonl"
    with dataset_path.open("w", encoding="utf-8") as handle:
        for row in grid["rows"]:
            handle.write(json.dumps(row, sort_keys=True) + "\n")

    records = [
        _record(row, grid, index)
        for index, row in enumerate(grid["rows"])
    ]
    partitions = {
        name: [record for record in records if record.split == name]
        for name in SPLITS
    }
    if any(not values for values in partitions.values()):
        raise RuntimeError("surrogate split contains an empty partition")

    torch.manual_seed(seed)
    random.seed(seed)
    config = ModelConfig(
        d_model=24,
        num_heads=2,
        protein_layers=1,
        molecule_layers=1,
        fusion_layers=1,
        protein_chunk_size=8,
        context_buckets=64,
        fba_context_dim=len(SCENARIO_FEATURE_IDS),
        dropout=0.0,
        use_protein=False,
        use_molecule=False,
        use_context=True,
        uncertainty_mode="fixed_variance_mse",
        task_names=("log10_flux",),
    )
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = BioCandidateRanker(config).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=2e-3)
    collator = EnzymeSubstrateCollator(
        context_buckets=config.context_buckets,
        fba_context_dim=config.fba_context_dim,
        task_names=config.task_names,
    )
    loaders = {
        name: DataLoader(
            RecordDataset(values), batch_size=16, shuffle=(name == "train"),
            collate_fn=collator,
        )
        for name, values in partitions.items()
    }

    best_validation = float("inf")
    best_state = None
    best_epoch = 0
    for epoch in range(1, epochs + 1):
        run_epoch(model, loaders["train"], device, optimizer)
        validation = run_epoch(model, loaders["validation"], device)
        if validation.loss < best_validation:
            best_validation = validation.loss
            best_epoch = epoch
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
    if best_state is not None:
        model.load_state_dict(best_state)

    train_metrics = run_epoch(model, loaders["train"], device)
    validation_metrics = run_epoch(model, loaders["validation"], device)
    test_metrics = run_epoch(model, loaders["test"], device)

    train_targets = [row["log10_growth"] for row in grid["rows"] if row["split"] == "train"]
    mean_target = sum(train_targets) / len(train_targets)
    test_rows = [row for row in grid["rows"] if row["split"] == "test"]
    mean_baseline_mse = sum(
        (row["log10_growth"] - mean_target) ** 2 for row in test_rows
    ) / len(test_rows)

    metrics = {
        "status": "surrogate_trained",
        "model_id": model_id,
        "objective_id": grid["objective_id"],
        "device": str(device),
        "epochs": epochs,
        "best_epoch": best_epoch,
        "seed": seed,
        "task": "log10_flux",
        "validation_tasks": {
            "log10_flux": {
                "count": len(partitions["validation"]),
                "rmse": math.sqrt(validation_metrics.loss),
            }
        },
        "feature_ids": grid["feature_ids"],
        "rows": {name: len(values) for name, values in partitions.items()},
        "dropped_scenarios": len(grid["dropped"]),
        "train_rmse_log10": math.sqrt(train_metrics.loss),
        "validation_rmse_log10": math.sqrt(validation_metrics.loss),
        "test_rmse_log10": math.sqrt(test_metrics.loss),
        "test_mean_baseline_rmse_log10": math.sqrt(mean_baseline_mse),
        "claim_boundary": SURROGATE_CLAIM_BOUNDARY,
    }
    save_checkpoint(
        output / "best.pt",
        model,
        optimizer,
        epoch=best_epoch,
        data_manifest={
            "surrogate_of": model_id,
            "model_sha256": config_file["sha256"],
            "dataset_rows": metrics["rows"],
            "dropped_scenarios": grid["dropped"],
            "feature_ids": grid["feature_ids"],
            "claim_boundary": SURROGATE_CLAIM_BOUNDARY,
            "fba_claim_boundary": FBA_CLAIM_BOUNDARY,
        },
        metrics=metrics,
    )
    (output / "metrics.json").write_text(json.dumps(metrics, indent=2) + "\n", encoding="utf-8")
    return metrics


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-id", default="iML1515", choices=sorted(MODEL_REGISTRY))
    parser.add_argument("--output-dir", default=None)
    parser.add_argument("--epochs", type=int, default=120)
    parser.add_argument("--seed", type=int, default=7)
    args = parser.parse_args()

    output_dir = args.output_dir or f"artifacts/fba-surrogate-{args.model_id}"
    metrics = train_surrogate(args.model_id, output_dir, epochs=args.epochs, seed=args.seed)
    print(json.dumps(metrics, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


SCENARIOS_BY_NAME: dict[str, dict[str, Any]] = {
    scenario["name"]: scenario
    for scenarios in (IML1515_SCENARIOS, IJO1366_SCENARIOS)
    for scenario in scenarios
}


def scenario_input_vector(
    model_id: str, preset: str, glucose: float, oxygen: float
) -> dict[str, Any]:
    """Build the surrogate's 8-wide fba_context input for one scenario.

    This is the inference-side counterpart of run_fba_grid: the workbench uses
    it to feed a scenario into a surrogate checkpoint through the ordinary
    prediction endpoint.
    """
    if preset not in SCENARIOS_BY_NAME:
        raise ValueError(
            f"unknown scenario {preset!r}; known: {sorted(SCENARIOS_BY_NAME)}"
        )
    scenario = SCENARIOS_BY_NAME[preset]
    if scenario.get("fusion") and model_id != "iJO1366":
        raise ValueError(f"scenario {preset!r} requires the iJO1366 fusion layer")
    features = list(_scenario_vector(scenario, glucose, oxygen))
    return {
        "features": features,
        "metadata": {
            "schema_version": 1,
            "feature_ids": list(SCENARIO_FEATURE_IDS),
            "model_id": model_id,
            "solver_id": "glpk",
            "objective_id": MODEL_REGISTRY[model_id]["objective_id"],
            "condition_id": _condition_hash(model_id, preset, glucose, oxygen),
        },
        "claim_boundary": SURROGATE_CLAIM_BOUNDARY,
    }
